# base 3.9.7 jdk 21
FROM maven:3.9.10-eclipse-temurin-24-alpine AS build_stage

WORKDIR /app_build

COPY pom.xml .

RUN mvn -e -B dependency:resolve
COPY src ./src

# Build the project and create the executable JAR
RUN mvn clean -e -B package -DskipTests
