name: Maven Build

on:
  push:
    paths:
      - '.mvn/wrapper/**'
      - 'pom.xml'
      - 'src/**'
  pull_request:
    paths:
      - '.mvn/wrapper/**'
      - 'pom.xml'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
          cache: 'maven'
      - name: Build with Maven
        run: ./mvnw -B clean package
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/